"use strict";

module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert("Renta", [
      {
        category_id: 1, // Комната
        title: "Уютная комната в центре",
        price: 15000,
        description: "Светлая и просторная комната с видом на парк.",
        photo: "http://localhost:3000/img/room1.jpg",
        location: "Москва, ул. Пушкина, д. 1",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        category_id: 1,
        title: "Комната с отдельным входом",
        price: 12000,
        description: "Удобное расположение, рядом метро.",
        photo: "http://localhost:3000/img/room2.jpg",
        location: "Москва, ул. Ленина, д. 5",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        category_id: 1,
        title: "Комната в коммунальной квартире",
        price: 8000,
        description: "Тихий район, рядом магазины.",
        photo: "http://localhost:3000/img/room3.jpg",
        location: "Москва, ул. Советская, д. 10",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        category_id: 2, // Квартира
        title: "Квартира в центре Москвы",
        price: 50000,
        description: "Трехкомнатная квартира с видом на Красную площадь.",
        photo: "http://localhost:3000/img/apartment1.jpg",
        location: "Москва, Красная площадь, д. 1",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        category_id: 2,
        title: "Однокомнатная квартира рядом с метро",
        price: 30000,
        description: "Комфортная квартира с мебелью и техникой.",
        photo: "http://localhost:3000/img/apartment2.jpg",
        location: "Москва, ул. Арбат, д. 15",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        category_id: 2,
        title: "Современная квартира в новом доме",
        price: 40000,
        description: "Просторная и светлая квартира с ремонтом.",
        photo: "http://localhost:3000/img/apartment3.jpg",
        location: "Москва, ул. Тверская, д. 20",
        points_latitude: 55.7576,
        points_longitude: 37.6139,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        category_id: 2,
        title: "Студия в центре",
        price: 25000,
        description: "Уютная студия, идеально для одного человека.",
        photo: "http://localhost:3000/img/room5.jpg",
        location: "Москва, ул. Большая Никитская, д. 25",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        category_id: 3, // Дом
        title: "Дом в Подмосковье",
        price: 100000,
        description: "Просторный дом с большим садом.",
        photo: "http://localhost:3000/img/house1.jpg",
        location: "Московская обл., д. Ивановка",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        category_id: 3,
        title: "Дом на берегу реки",
        price: 120000,
        description: "Дом с красивым видом на природу.",
        photo: "http://localhost:3000/img/house2.jpg",
        location: "Московская обл., д. Озерки",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        category_id: 3,
        title: "Загородный коттедж",
        price: 150000,
        description: "Современный коттедж с бассейном.",
        photo: "http://localhost:3000/img/house3.jpg",
        location: "Московская обл., д. Солнечное",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        category_id: 3,
        title: "Уютный домик в лесу",
        price: 80000,
        description: "Идеальное место для отдыха на природе.",
        photo: "http://localhost:3000/img/house4.jpg",
        location: "Московская обл., д. Зеленая Роща",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        category_id: 2,
        title: "Двухкомнатная квартира в новостройке",
        price: 45000,
        description: "Квартира с новой мебелью и техникой.",
        photo: "http://localhost:3000/img/apartment4.jpg",
        location: "Москва, ул. Мира, д. 35",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        category_id: 1,
        title: "Комната на длительный срок",
        price: 10000,
        description: "Комната в центре с мебелью.",
        photo: "http://localhost:3000/img/room4.jpg",
        location: "Москва, ул. Новая, д. 50",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        category_id: 2,
        title: "Трехкомнатная квартира в старом фонде",
        price: 35000,
        description: "Квартира с высокими потолками и большими окнами.",
        photo: "http://localhost:3000/img/apartment5.jpg",
        location: "Москва, ул. Воронцова, д. 8",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        category_id: 3,
        title: "Современный коттедж с гаражом",
        price: 170000,
        description: "Дом для большой семьи, рядом лес и речка.",
        photo: "http://localhost:3000/img/house5.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("Renta", null, {});
  },
};
